name: nft_marketplace
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_circular_text: ^0.3.1
  google_fonts: ^4.0.4
  bottom_navy_bar: ^6.0.0
  flutter_lorem: ^2.0.0
  dotted_border: ^2.0.0+3
  fluttermoji: ^1.0.2
  empty_widget: ^0.0.5
  turn_page_transition: ^0.3.0
  animated_text_kit: ^4.2.2
  web3dart: ^2.6.1
  provider: ^6.0.5
  http: ^0.13.6
  web_socket_channel: ^2.4.0
  dio: ^5.1.2
  image_picker: ^0.7.2+1
  status_alert: ^1.0.1
  select_card: ^0.0.9
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/json/abi.json